weights = { # weights by road type
    'residential': 1,
    'living_street': 1,
    'tertiary_link': 1,
    'secondary_link': 2,
    'primary_link': 3,
    'tertiary': 2,
    'secondary': 3,
    'primary': 4,
    'motorway_link': 4,
    'motorway': 5,
    'trunk_link': 1,
    'trunk': 1,
    'rest_area': 1,
    'unclassified': 1,
    'disused': 1,
    'destroyed': 5, # bridge (highway)
    "['secondary', 'trunk_link']": 3,
    "['residential', 'tertiary']": 2,
    "['secondary', 'tertiary']": 3,
    "['residential', 'unclassified']": 1,
    "['unclassified', 'tertiary']": 2,
    "['secondary', 'secondary_link']": 3,
    "['unclassified', 'primary_link']": 3,
    "['residential', 'primary_link']": 3,
    "['tertiary', 'primary_link']": 3,
    "['primary', 'motorway']": 5,
    "['residential', 'living_street']": 1,
    "['motorway_link', 'motorway']": 5,
    "['motorway_link', 'tertiary']": 4,
    "['motorway_link', 'primary']": 4,
    "['disused', 'unclassified']": 1,
    "['tertiary', 'tertiary_link']": 2,
    "['primary', 'primary_link']": 4,
    "['motorway', 'trunk']": 5,
    "['primary', 'tertiary']": 4,
    "['motorway_link', 'tertiary_link']": 4,
    "['residential', 'trunk_link']": 1,
    "['residential', 'motorway_link']": 4,
    "['residential', 'secondary_link']": 2,
    "['disused', 'residential']": 1,
    "['motorway_link', 'trunk_link']": 4,
    "['unclassified', 'trunk_link']": 1,
    "['unclassified', 'residential']": 1,
    "['living_street', 'residential']": 1,
    "['tertiary', 'residential']": 2,
    "['primary', 'motorway_link']": 4,
    "['tertiary', 'secondary']": 3,
    "['primary_link', 'residential']": 3
}
